name: Monorepo Orchestrator

# El pipeline se activa cuando se hace un push o pull request en la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Su único trabajo es escanear qué ha cambiado
  changes:
    name: "Detectar Cambios en Componentes"
    runs-on: ubuntu-latest
    # Guardamos los resultados en variables (outputs) para que otros jobs los lean
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      # Usamos una acción estándar para mapear los directorios del monorepo
      - name: Evaluar filtros de ruta
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            infra:
              - 'infraestructura/**'
    # Job 2: Pipeline simulado para el Frontend
    frontend-pipeline:
        name: "Pipeline Frontend"
        needs: changes # Espera a que termine el detector
        if: ${{ needs.changes.outputs.frontend == 'true' }} # Solo corre si cambió el frontend
        runs-on: ubuntu-latest
        steps:
            - name: Instalar y Compilar Frontend
            run: echo "Ejecutando pruebas y build del componente Frontend..."
    # Job 3: Pipeline simulado para el Backend
    backend-pipeline:
        name: "Pipeline Backend"
        needs: changes
        if: ${{ needs.changes.outputs.backend == 'true' }} # Solo corre si cambió el backend
        runs-on: ubuntu-latest
        steps:
            - name: Testear API Backend
            run: echo "Ejecutando pruebas unitarias del componente Backend..."

    # Job 4: Pipeline simulado para la Infraestructura
    infra-pipeline:
        name: "Pipeline Infraestructura"
        needs: changes
        if: ${{ needs.changes.outputs.infra == 'true' }} # Solo corre si cambió la infraestructura
        runs-on: ubuntu-latest
        steps:
            - name: Validar Infraestructura
            run: echo "Ejecutando validacion de scripts de infraestructura..."