name: Monorepo Orchestrator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # El detector de cambios que ya configuramos en la Parte 2
  changes:
    name: "Detectar Cambios en Componentes"
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Evaluar filtros de ruta
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            infra:
              - 'infraestructura/**'

  # OPTIMIZACIÓN: Llamadas condicionales a la plantilla reutilizable
  frontend-pipeline:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/ci-template.yml
    with:
      component_name: "Frontend Application"

  backend-pipeline:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/ci-template.yml
    with:
      component_name: "Backend API"

  infra-pipeline:
    needs: changes
    if: ${{ needs.changes.outputs.infra == 'true' }}
    uses: ./.github/workflows/ci-template.yml
    with:
      component_name: "Cloud Infrastructure"